SNS/urls.py
from django.urls import path
from . import views

app_name = 'SNS'

urlpatterns = [
    
    # Main
    path('', views.index, name='index'),
    path('home/', views.home, name='home'), 
    path('search/', views.search, name='search'),
    path('search/song/<slug:track_id>', views.song, name='song'),
    path('search/album/<slug:album_id>', views.album, name='album'),
    path('search/artist/<slug:artist_id>', views.artist, name='artist'),
    path('search/playlist/<slug:playlist_id>', views.playlist, name='playlist'),
    path('post/', views.post, name='post'),
    path('post/good', views.postGood, name='postgood'),
    path('post/delete', views.postDelete, name='postdelete'),
    path('spotify', views.spotify, name='spotify'),
    path('spotify/auth/manually', views.spotify_auth_manually, name='spotify_auth_manually'),
    path('spotify/callback', views.spotify_callback, name='spotify_callback'),
    path('library/song', views.library_song, name='library_song'),
    path('library/artist', views.library_artist, name='library_artist'),
    path('library/album', views.library_album, name='library_album'),
    path('library/playlist', views.library_playlist, name='library_playlist'),
    path('profile/<slug:username>', views.profile, name='profile'),
    path('profile/<slug:username>/edit', views.profile_edit, name='profile_edit'),
    path('profile/<slug:username>/delete', views.profile_delete, name='profile_delete'),
    path('profile/<slug:username>/song/follow', views.user_song, name='song_follow'),
    path('profile/<slug:username>/user/follow', views.user_follow, name='user_follow'),
    path('profile/<slug:username>/user/follower', views.user_follower, name='user_follower'),
    
    # Json Response
    path('check/username/', views.username_check, name='username_check'),
    path('search/song/', views.search_song, name='search_song'),
    path('search/any/', views.search_any, name='search_any'),
    path('follow/all/', views.follow_all, name='follow_all'),
    
    # Account
    path('signup/', views.AccountRegistration.as_view(), name='signup'), 
    path('signin/', views.Signin, name='signin'), 
    path('signout/', views.Signout, name='signout'),
    
    # CSRF Token
    path('csrf_token/', views.csrf_token, name='csrf_token'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('SNS.urls')),
]

SNS/models.py
from django.db import models
from django.contrib.auth.models import User

class ProfileData(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    icon = models.URLField()
    description = models.TextField(max_length=300)
    spotify_id = models.CharField(max_length=100, null=True)
    spotify_premium = models.BooleanField(default=False)
    spotify_access_token = models.CharField(max_length=100, null=True)
    spotify_refresh_token = models.CharField(max_length=100, null=True)
    def __str__(self):
        return self.user.username

class MusicFollowData(models.Model):
    user_id = models.IntegerField()
    music_id = models.CharField(max_length=100)
    song_name = models.CharField(max_length=100)
    artist_name = models.CharField(max_length=100)
    album_name = models.CharField(max_length=100)
    image = models.URLField()

class UserFollowData(models.Model):
    user_id = models.IntegerField()
    opponent_id = models.IntegerField()

class PostData(models.Model):
    user_id = models.IntegerField()
    contents = models.TextField(max_length=500)
    music_id = models.CharField(max_length=100)
    original_post_id = models.IntegerField(null=True)
    song_name = models.CharField(max_length=100)
    artist_name = models.CharField(max_length=100)
    album_name = models.CharField(max_length=100)
    image = models.URLField()
    created_at = models.DateTimeField(auto_now_add=True)

class GoodData(models.Model):
    post_id = models.IntegerField()
    gooded_id = models.IntegerField()
    admin_id = models.IntegerField()

SNS/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import ProfileData

class ProfileForm(forms.ModelForm):
    
    password = forms.CharField(widget=forms.PasswordInput(), label='Password')
    
    class Meta():
        model = User
        fields = ['username', 'email', 'password']
        labels = {
            'username': 'Username',
            'email': 'Email',
            'password': 'Password'
        }
        widgets = {
            'icon': forms.URLInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'spotify_access_token': forms.TextInput(attrs={'class': 'form-control'}),
            'spotify_refresh_token': forms.TextInput(attrs={'class': 'form-control'}),
        }

class AddProfileForm(forms.ModelForm):
    
    class Meta():
        model = ProfileData
        fields = ['icon', 'description', 'spotify_id', 'spotify_access_token', 'spotify_refresh_token']
        labels = {
            'icon': 'Icon',
            'description': 'Description',
            'spotify_id': 'Spotify ID',
            'spotify_access_token': 'Spotify Access Token',
            'spotify_refresh_token': 'Spotify Refresh Token',
        }

SNS/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse, QueryDict
from django.contrib.auth import authenticate, login, logout
from django.views.generic import TemplateView
from django.middleware.csrf import get_token
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.db.models import Q
import boto3, random, string, json
from io import BytesIO
from PIL import Image
from . import spotify_data
from .constants import *
from .models import *
from .forms import AddProfileForm, ProfileForm


# Create your views here.

def index(request):
    
    HOST_URL = request._current_scheme_host
    
    return redirect(HOST_URL + '/home/')

def home(request):
    
    if request.method == 'GET':
        
        if 'loaded_items' in request.GET:
            
            loaded_items = request.GET['loaded_items']
            
            items = PostData.objects.all().order_by('-created_at')[int(loaded_items):int(loaded_items) + 100]
            
            return JsonResponse({ 'response': items })
        
        latest_music_ids = PostData.objects.values('music_id').annotate(latest_created_at=models.Max('created_at'))
        items = PostData.objects.filter(created_at__in=latest_music_ids.values('latest_created_at')).order_by('created_at').reverse()[:100]
        
        return render(request, 'SNS/home.html', { 
            'items': items, 
        })


def search(request):
    
    if request.method == 'GET':
        
        return render(request, 'SNS/search.html')


def song(request, track_id):
    
    if request.method == 'GET':
        
        response = spotify_data.search_track_id(track_id)
        
        if response['status']['one'] == True:
            
            follow = MusicFollowData.objects.filter(user_id=request.user.id, music_id=track_id).exists()
            
            followers = MusicFollowData.objects.filter(music_id=track_id).count()
            
            posts_data = PostData.objects.filter(Q(music_id=track_id) & Q(original_post_id=None)).order_by('-created_at')
            
            posts = []
            
            for post in posts_data:
                
                replies_data = PostData.objects.filter(original_post_id=post.id).order_by('-created_at')
                
                replies = []
                
                for reply in replies_data:
                    
                    user = User.objects.get(id=reply.user_id)
                    
                    replies.append({
                        'id': reply.id,
                        'user_icon': ProfileData.objects.get(user_id=reply.user_id).icon,
                        'username': user.username,
                        'user_id': post.user_id,
                        'date': reply.created_at,
                        'good': GoodData.objects.filter(post_id=reply.id).count(),
                        'good_status': GoodData.objects.filter(post_id=reply.id, gooded_id=request.user.id).exists(),
                        'text': reply.contents,
                    })
                
                user = User.objects.get(id=post.user_id)
                
                posts.append({
                    'id': post.id,
                    'user_icon': ProfileData.objects.get(user_id=post.user_id).icon,
                    'username': user.username,
                    'user_id': post.user_id,
                    'date': post.created_at,
                    'good': GoodData.objects.filter(post_id=post.id).count(),
                    'good_status': GoodData.objects.filter(post_id=post.id, gooded_id=request.user.id).exists(),
                    'text': post.contents,
                    'replies': replies,
                })
            
            en_response = spotify_data.search_track_id(track_id, 'en')
            
            same_response = spotify_data.search_track_artist(SPOTIFY_SEARCH_TYPE_TRACK, en_response['data'][0]['song']['name'], en_response['data'][0]['artist'][0]['name'], 20, 0)
            
            return render(request, 'SNS/song.html', { 
                'response': response, 
                'same_response': same_response,
                'same': same_response['status']['total'] >= 2,
                'follow': follow,
                'followers': followers,
                'posts': posts,
            })
    
    elif request.method == 'POST':
        
        HOST_URL = request._current_scheme_host
        
        song = spotify_data.search_track_id(track_id)
        
        follow = MusicFollowData.objects.filter(user_id=request.user.id, music_id=track_id).exists()
        
        if follow:
            MusicFollowData.objects.filter(user_id=request.user.id, music_id=track_id).delete()
        
        else:
            MusicFollowData.objects.create(
                user_id = request.user.id,
                music_id = track_id,
                song_name = song['data'][0]['song']['name'],
                artist_name = song['data'][0]['artist'][0]['name'],
                album_name = song['data'][0]['album']['name'],
                image = song['data'][0]['album']['image'],
            )
        
        return redirect(HOST_URL + '/search/song/' + track_id)


def album(request, album_id):
    
    if request.method == 'GET':
        
        response = spotify_data.search_album_id(album_id)
        
        return render(request, 'SNS/album.html', {
            'response': response,
        })


def artist(request, artist_id):
    
    if request.method == 'GET':
        
        response = spotify_data.search_artist_id(artist_id)
        
        return render(request, 'SNS/artist.html', {
            'response': response,
        })


def playlist(request, playlist_id):
    
    if request.method == 'GET':
        
        user = ProfileData.objects.get(user_id=request.user.id)
        
        response = spotify_data.search_playlist_id(playlist_id, user.spotify_access_token, request)
        
        return render(request, 'SNS/playlist.html', {
            'response': response,
        })


@login_required
def post(request):
    
    if request.method == 'GET':
        
        song_data = {
            'song': {'name': '', 'id': '', 'preview': ''},
            'artist': [{'name': '', 'id': ''}],
            'album': {'name': '', 'id': '', 'image': ''}
        }
        
        song = False
        post = None
        reply_to = None
        recent_play = { 'data': [] }
        recent = False
        
        if 'song_id' in request.GET:
            
            song_data = spotify_data.search_track_id(request.GET['song_id'])['data'][0]
            song = True
        
        else:
            
            access_token = ProfileData.objects.get(user_id=request.user.id).spotify_access_token
            
            if access_token != None:
                recent_play = spotify_data.get_recent_play(access_token, request, 50)
                recent = True
        
        if 'post_id' in request.GET:
            
            post_check = PostData.objects.get(id=request.GET['post_id'])
            if post_check.user_id == request.user.id:
                post = post_check
        
        if 'reply_to' in request.GET:
            
            reply_to = request.GET['reply_to']
        
        return render(request, 'SNS/post.html', {
            'song': song_data,
            'response': song,
            'post': post,
            'reply_to': reply_to,
            'recent_song': recent_play['data'],
            'recent': recent,
        })
    
    elif request.method == 'POST':
        HOST_URL = request._current_scheme_host
        song_id = request.POST['song']
        response = spotify_data.search_track_id(song_id)
        
        if 'post_id' in request.POST:
            post = PostData.objects.get(id=request.POST['post_id'])
            if post.user_id == request.user.id:
                post.contents = request.POST['content']
                post.save()
        
        else:
            if 'reply_to' in request.POST:
                reply_to = request.POST['reply_to']
            else:
                reply_to = None
            
            PostData.objects.create(
                user_id = request.user.id,
                contents = request.POST['content'],
                music_id = song_id,
                song_name = response['data'][0]['song']['name'],
                artist_name = response['data'][0]['artist'][0]['name'],
                album_name = response['data'][0]['album']['name'],
                image = response['data'][0]['album']['image'],
                original_post_id = reply_to,
            )
        
        return redirect(HOST_URL + '/search/song/' + song_id)


@login_required
def postGood(request):
    
    if request.method == 'GET':
        
        if 'status' in request.GET and 'post_id' in request.GET and 'user_id' in request.GET and 'posted_id' in request.GET:
            
            status = request.GET['status']
            post_id = request.GET['post_id']
            user_id = request.GET['user_id']
            posted_id = request.GET['posted_id']
            
            if status == 'good':
                GoodData.objects.create(
                    gooded_id = int(user_id),
                    post_id = int(post_id),
                    admin_id = int(posted_id),
                )
            else:
                GoodData.objects.filter(gooded_id=user_id, post_id=post_id).delete()
            
            count = GoodData.objects.filter(post_id=post_id).count()
            
            return JsonResponse({
                'success': True,
                'create': status == 'good',
                'count': count,
            })
        
        else:
            return JsonResponse({ 'status': 'failed' })
    
    else:
        return JsonResponse({ 'status': 'failed' })


@login_required
def postDelete(request):
    

templates/SNS/library-playlist.html
{% extends "SNS/library.html" %}
{% load static %}
{% load humanize %}
{% block library-content %}
    <table class="margin-auto" id="search-result-table-tracks">
        {% for playlist in response.playlist %}
            <tr>
                <td class="song-table-img"><img src="{{ playlist.image }}" id="img" class="new-post-song-img" alt="{{ playlist.name }}"></td>
                <td class="song-table-title">
                    <div class="search-song-title-artist new-post-song-title-artist">
                        <a href="{% url "SNS:playlist" playlist.id %}"><p class="new-post-song-title dont-new-line">{{ playlist.name }}</p></a>
                        <a href="{% url "SNS:playlist" playlist.id %}"><p class="new-post-song-artist dont-new-line">{{ playlist.owner.name }}</p></a>
                    </div>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/SNS/profile-edit.html
{% extends "SNS/layout.html" %}
{% load static %}
{% block title %}Edit Profile{{ block.super }}{% endblock %}
{% block main %}
<div class="main">
    <div id="new-post-text">
        <h1 class="new-post-title">Edit Profile</h1>
        <div class="signup-form">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-content">
                    <h2>Icon</h2>
                    <img src="{{ profile.icon }}" class="song-coverart">
                    <input type="file" name="icon" style="display:block" accept="image/*">
                </div>
                <div class="form-content">
                    <h2>Description</h2>
                    <textarea name="description" cols="40" rows="10" maxlength="300" id="id_description" placeholder="自己紹介を入力...">{% if profile.description != "None" %}{{ profile.description }}{% endif %}</textarea>
                </div>
                <div class="signup-parent">
                    <button class="new-post-submit" style="color: red;" type="button" onclick="location.href = '{% url "SNS:profile_delete" request.user.username %}';">Delete Account</button><br>
                    <input type="submit" value="Save" id="signup" class="new-post-submit">
                </div>
            </form>
        </div>
    </div>
    <script src={% static 'SNS/signup.js' %}></script>
</div>
{% endblock %}

templates/SNS/profile-post.html
{% extends "SNS/profile.html" %}
{% load static %}
{% load humanize %}
{% block title %}{{ request.user.username }}さんの投稿{{ block.super }}{% endblock %}
{% block profile %}
<div class="main">
    <div class="post">
        <div class="post-top">
            <h2 class="post-title">投稿({{ posts | length | intcomma }})</h2>
        </div>
            {% for post in posts %}
                <div class="post-detail">
                    <div class="post-user">
                        <img src="{{ profile.icon }}" class="profile-icon post-profile-icon">
                        <a href="{% url 'SNS:profile' post.username %}" class="post-username">{{ post.username }}</a>
                        <p class="post-date">{{ post.date | naturaltime }}</p>
                    </div>
                    <p class="post-text">{{ post.text }}</p>
                    <table class="margin-auto">
                        <tr>
                            <td class="song-table-img"><img src="{{ post.image }}" id="img" class="new-post-song-img" alt="{{ post.song }}"></td>
                            <td class="song-table-title">
                                <div class="search-song-title-artist new-post-song-title-artist">
                                    <a href="{% url "SNS:song" post.song_id %}"><p class="new-post-song-title dont-new-line">{{ post.song }}</p>
                                    <a href="{% url "SNS:song" post.song_id %}"><p class="new-post-song-artist dont-new-line">{{ post.artist }} / {{ post.album }}</p>
                                </div>
                            </td>
                        </tr>
                    </table>
                    <div class="post-reaction">
                        {% if post.good_status %}
                            <button class="post-reaction-button liked" type="button" id="good-{{ post.id }}" onclick="good('gooded', '{{ post.id }}', '{{ request.user.id }}', '{{ post.user_id }}');"> {{ post.good | intcomma }}</button>
                        {% else %}
                            <button class="post-reaction-button like" type="button" id="good-{{ post.id }}" onclick="good('good', '{{ post.id }}', '{{ request.user.id }}', '{{ post.user_id }}');"> {{ post.good | intcomma }}</button>
                        {% endif %}
                        <button class="post-reaction-button comment" type="button" onclick="location.href='{% url 'SNS:post' %}?reply_to={{ post.id }}&song_id={{ post.song_id }}';"> {{ post.replies | length }}</button>
                        {% if post.username == request.user.username %}
                            <button class="post-reaction-button edit" type="button" onclick="location.href='{% url 'SNS:post' %}?post_id={{ post.id }}&song_id={{ post.song_id }}';"></button>
                            <button class="post-reaction-button delete" type="button" onclick="deletePost('{{ post.id }}', '{{ request.user.id }}');"></button>
                        {% endif %}
                    </div>
                </div>
            {% empty %}
                <div class="home-no-post">
                    <h1>投稿がありません</h1>
                </div>
            {% endfor %}
        </div>
    <script src="{% static 'SNS/song.js' %}"></script>
</div>
{% endblock %}

templates/SNS/profile.html
{% extends "SNS/layout.html" %}
{% load static %}
{% load humanize %}
{% block main %}
    <div class="main">
        <div class="song">
            <span class="song-details">
                <img src="{{ profile.icon }}" alt="{{ user_obj.username }}" class="song-coverart prof-icon">
                <h1 class="song-detail song-title">{{ user_obj.username }}</h1>
            </span>
            {% if request.user.username != user_obj.username %}
                {% if user.is_authenticated %}
                <form action="{% url "SNS:profile" user_obj.id %}" method="post">
                    {% csrf_token %}
                    {% if follow %}
                        <input type="hidden" name="status" value="true">
                        <input type="hidden" name="user_id" value="{{ user_obj.id }}">
                        <input class="song-detail song-follow" type="submit" value="フォロー解除">
                    {% else %}
                        <input type="hidden" name="status" value="false">
                        <input type="hidden" name="user_id" value="{{ user_obj.id }}">
                        <input class="song-detail song-follow" type="submit" value="ユーザーをフォロー">
                    {% endif %}
                </form>
                {% else %}
                <button id="search-button-tracks" class="song-detail song-follow" type="button" onclick="location.href = '{% url "SNS:signin" %}?next=/profile/{{ user_obj.username }}';">フォローにはログインが必要です</button>
                {% endif %}
            {% else %}
                <button class="song-detail song-follow" type="button" onclick="location.href = '{% url "SNS:profile_edit" request.user.username %}';">プロフィールを編集</button>
            {% endif %}
            <p class="song-detail song-follower song-artist-album-follower"><a href="{% url "SNS:song_follow" user_obj.username %}">{{ song_follow }} 曲フォロー</a> ・ <a href="{% url "SNS:user_follow" user_obj.username %}">{{ user_follow | intcomma }} ユーザーフォロー</a> ・ <a href="{% url "SNS:user_follower" user_obj.username %}">{{ follower | intcomma }} フォロワー</a></p>
        </div>
        <div class="center">
            {% if profile.description != 'None' %}
                <p>{{ profile.description }}</p>
            {% endif %}
        </div>
        {% block profile %}
        {% endblock %}
    </div>
{% endblock %}

templates/SNS/song.html
{% extends "SNS/layout.html" %}
{% load static %}
{% load humanize %}
{% block title %}{{ response.data.0.song.name }} / {% for artist in response.data.0.artist %}{% if forloop.last %}{{ artist.name }}{% else %}{{ artist.name }}, {% endif %}{% endfor %}{{ block.super }}{% endblock %}
{% block main %}
    <div class="main">
        <div class="song">
            <span class="song-details">
                <img src="{{ response.data.0.album.image }}" alt="{{ response.data.0.song.name }}" class="song-coverart">
                <h1 class="song-detail song-title">{{ response.data.0.song.name }}</h1>
                <p class="song-detail song-artist-album song-artist-album-follower">
                    {% for artist in response.data.0.artist %}
                        {% if forloop.last %}
                            <a href="{% url "SNS:artist" artist.id %}">{{ artist.name }}</a>
                        {% else %}
                            <a href="{% url "SNS:artist" artist.id %}">{{ artist.name }}</a>, 
                        {% endif %}
                    {% endfor %}
                     / <a href="{% url "SNS:album" response.data.0.album.id %}">{{ response.data.0.album.name }}</a></p>
                {% if user.is_authenticated %}
                    <form action="" method="post">
                        {% csrf_token %}
                        {% if follow %}
                            <input type="hidden" name="status" value="true">
                            <input type="hidden" name="song_id" value="{{ response.data.0.song.id }}">
                            <input class="song-detail song-follow" type="submit" value="フォロー解除">
                        {% else %}
                            <input type="hidden" name="status" value="false">
                            <input type="hidden" name="song_id" value="{{ response.data.0.song.id }}">
                            <input class="song-detail song-follow" type="submit" value="楽曲をフォロー">
                        {% endif %}
                    </form>
                {% else %}
                <button id="search-button-tracks" class="song-detail song-follow" type="button" onclick="location.href = '{% url "SNS:signin" %}?next=/search/song/{{ response.data.0.song.id }}';">フォローにはログインが必要です</button>
                {% endif %}
                <p class="song-detail song-follower song-artist-album-follower">{{ followers | intcomma }}人がフォロー</p>
            </span>
            <iframe class="song-preview" src="https://open.spotify.com/embed/track/{{ response.data.0.song.id }}?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
        </div>
        {% if same %}
            <div class="center">
                <h2 id="record-song">他のアルバムに収録された同一楽曲</h2>
                <table class="margin-auto">
                    {% for song in same_response.data %}
                        {% if song.song.id != response.data.0.song.id %}
                            <tr>
                                <td class="song-table-img"><img src="{{ song.album.image }}" id="img" class="new-post-song-img" alt="{{ song.song.name }}"></td>
                                <td class="song-table-title">
                                    <div class="search-song-title-artist new-post-song-title-artist">
                                        <a href="{% url "SNS:song" song.song.id %}"><p class="new-post-song-title dont-new-line">{{ song.song.name }}</p>
                                        <a href="{% url "SNS:song" song.song.id %}"><p class="new-post-song-artist dont-new-line">{% for artist in song.artist %}{% if forloop.last %}{{ artist.name }}{% else %}{{ artist.name }}, {% endif %}{% endfor %} / {{ song.album.name }}</p>
                                    </div>
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </table>
            </div>
        {% endif %}
        <div class="post">
            <div class="post-top">
                <h2 class="post-title">投稿({{ posts | length | intcomma }})</h2>
                <a href="{% url 'SNS:post' %}?song_id={{ response.data.0.song.id }}"><span class="post-add"><i class="fa-solid fa-plus"></i></span></a>
                <a href="{% url 'SNS:song' response.data.0.song.id %}" class="post-sort">新しい順</a>
            </div>
            {% for post in posts %}
                <div class="post-detail">
                    <div class="post-user">
                        <img src="{{ post.user_icon }}" class="profile-icon post-profile-icon">
                        <a href="{% url 'SNS:profile' post.username %}" class="post-username">{{ post.username }}</a>
                        <p class="post-date">{{ post.date | naturaltime }}</p>
                    </div>
                    <p class="post-text">{{ post.text }}</p>
                    <div class="post-reaction">
                        {% if post.good_status %}
                            <button class="post-reaction-button liked" type="button" id="good-{{ post.id }}" onclick="good('gooded', '{{ post.id }}', '{{ request.user.id }}', '{{ post.user_id }}');"> {{ post.good | intcomma }}</button>
                        {% else %}
                            <button class="post-reaction-button like" type="button" id="good-{{ post.id }}" onclick="good('good', '{{ post.id }}', '{{ request.user.id }}', '{{ post.user_id }}');"> {{ post.good | intcomma }}</button>
                        {% endif %}
                        <button class="post-reaction-button comment" type="button" onclick="location.href='{% url 'SNS:post' %}?reply_to={{ post.id }}&song_id={{ response.data.0.song.id }}';"> {{ post.replies | length }}</button>
                        {% if post.username == request.user.username %}
                            <button class="post-reaction-button edit" type="button" onclick="location.href='{% url 'SNS:post' %}?post_id={{ post.id }}&song_id={{ response.data.0.song.id }}';"></button>
                            <button class="post-reaction-button delete" type="button" onclick="deletePost('{{ post.id }}', '{{ request.user.id }}');"></button>
                        {% endif %}
                    </div>
                </div>
                {% for reply in post.replies %}
                    <div class="post-detail-reply">
                        <div class="post-user">
                            <img src="{{ reply.user_icon }}" class="profile-icon post-profile-icon">
                            <a href="{% url 'SNS:profile' reply.username %}" class="post-username">{{ reply.username }}</a>
                            <p class="post-date">{{ reply.date | naturaltime }}</p>
                        </div>
                        <p class="post-text">{{ reply.text }}</p>
                        <div class="post-reaction">
                            {% if reply.good_status %}
                                <button class="post-reaction-button liked" type="button" id="good-{{ reply.id }}" onclick="good('gooded', '{{ reply.id }}', '{{ request.user.id }}', '{{ reply.user_id }}');"> {{ reply.good | intcomma }}</button>
                            {% else %}
                                <button class="post-reaction-button like" type="button" id="good-{{ reply.id }}" onclick="good('good', '{{ reply.id }}', '{{ request.user.id }}', '{{ reply.user_id }}');"> {{ reply.good | intcomma }}</button>
                            {% endif %}
                            {% if reply.username == request.user.username %}
                                <button class="post-reaction-button edit" type="button" onclick="location.href='{% url 'SNS:post' %}?post_id={{ reply.id }}&song_id={{ response.data.0.song.id }}';"></button>
                                <button class="post-reaction-button delete" type="button" onclick="deletePost('{{ reply.id }}', '{{ request.user.id }}');"></button>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            {% empty %}
                <div class="home-no-post">
                    <h1>投稿がありません</h1>
                </div>
            {% endfor %}
        </div>
    </div>
    <script src="{% static 'SNS/song.js' %}"></script>
{% endblock %}